# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter:  postgresql
  host:     ec2-54-246-90-10.eu-west-1.compute.amazonaws.com
  encoding: unicode
  database: d32hc26qvl3dqb
  pool:     5
  username: axyggpyuyhtjli
  port: 5432
  uri: postgres://axyggpyuyhtjli:0f8a7c66eeff79bd69d109ef0e0dc7e8aad6d43b445b7415e9d2816053cfa824@ec2-54-246-90-10.eu-west-1.compute.amazonaws.com:5432/d32hc26qvl3dqb
  password: 0f8a7c66eeff79bd69d109ef0e0dc7e8aad6d43b445b7415e9d2816053cfa824
  template: template0

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: v3cube_test
  pool:     5
  username: postgres
  password: root
  template: template0

production:
  adapter:  postgresql
  host:     ec2-54-246-90-10.eu-west-1.compute.amazonaws.com
  encoding: unicode
  database: d32hc26qvl3dqb
  pool:     5
  username: axyggpyuyhtjli
  port: 5432
  uri: postgres://axyggpyuyhtjli:0f8a7c66eeff79bd69d109ef0e0dc7e8aad6d43b445b7415e9d2816053cfa824@ec2-54-246-90-10.eu-west-1.compute.amazonaws.com:5432/d32hc26qvl3dqb
  password: 0f8a7c66eeff79bd69d109ef0e0dc7e8aad6d43b445b7415e9d2816053cfa824
  template: template0
